# Alias utiles pour l'utilisateur ansible
# Ce fichier est déployé automatiquement sur toutes les VMs

# Alias de base pour ls
alias ll='ls -alFh --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias ls='ls --color=auto'

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Affichage amélioré
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'

# Sécurité
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Informations système
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'

# Gestion des services
alias sctl='systemctl'
alias sctls='systemctl status'
alias sctlr='systemctl restart'
alias sctlstart='systemctl start'
alias sctlstop='systemctl stop'

# Docker (si installé)
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias dlog='docker logs'
alias dexec='docker exec -it'

# Git (si installé)
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'
alias gd='git diff'

# Logs
alias tailf='tail -f'
alias logs='journalctl -xe'
alias logsf='journalctl -f'

# Réseau
alias ports='netstat -tulanp'
alias listening='lsof -i -P -n | grep LISTEN'

# Historique
alias h='history'
alias hg='history | grep'

# Disk usage
alias ducks='du -cks * | sort -rn | head'

# Édition rapide
alias vi='vim'
alias nano='nano -c'

# Top amélioré si htop est installé
if command -v htop &> /dev/null; then
    alias top='htop'
fi

# Bat pour cat si disponible
if command -v bat &> /dev/null; then
    alias cat='bat'
fi

# Reload des alias
alias reload='source ~/.bashrc'
