# Inventaire Ansible généré automatiquement par Terraform
# Ne pas modifier manuellement - ce fichier sera écrasé

# Groupes par type de serveur
[prod]
dolibarr-prod01 ansible_host=192.168.1.101 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_ecdsa

[preprod]
dolibarr-preprod01 ansible_host=192.168.1.111 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_ecdsa

# Groupe global
[all:children]
prod
preprod

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
