---
- name: System update
  hosts: all
  become: true
  
  vars:
    dolibarr_version: "22.0.3"
    dolibarr_full_version: "dolibarr_22.0.3-4_all.deb"

  tasks:
    - name: "Download dolibarr 'dolideb' version {{dolibarr_version }}"
      ansible.builtin.get_url:
        url: "https://sourceforge.net/projects/dolibarr/files/Dolibarr%20installer%20for%20Debian-Ubuntu%20%28DoliDeb%29/{{dolibarr_version}}/{{dolibarr_full_version}}/download"
        dest: "/tmp/{{dolibarr_full_version}}"
        mode: '0644'
        force: false
      register: download_result

    - name: "Fix broken packages and install dependencies"
      ansible.builtin.command: apt-get install /tmp/{{dolibarr_full_version}} -f -y
      environment:
        DEBIAN_FRONTEND: noninteractive
        DEBCONF_NONINTERACTIVE_SEEN: "true"


    # - name: "Fix broken dependencies before installation"
    #   ansible.builtin.apt:
    #     state: fixed

    # - name: "Install dolibarr 'dolideb' package {{dolibarr_version }}"
    #   ansible.builtin.apt:
    #     deb: /tmp/{{dolibarr_full_version}}
    #     state: present
    #     install_recommends: true
    #   notify:
    #     - Restart Apache
    #   ignore_errors: true
    #   register: install_result

    # - name: "Fix dependencies if installation failed"
    #   ansible.builtin.apt:
    #     state: fixed
    #   when: install_result.failed

    # - name: "Retry installation after fix"
    #   ansible.builtin.apt:
    #     deb: /tmp/{{dolibarr_full_version}}
    #     state: present
    #   when: install_result.failed
    #   notify:
    #     - Restart Apache

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted  


        